# Generated by Django 6.0.3 on 2026-03-23 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='modele_3d',
            field=models.FileField(blank=True, null=True, upload_to='modeles_3d/'),
        ),
        migrations.CreateModel(
            name='PhotoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_biens/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_bien', to='patrimoine.bien')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='photos_upload',
            field=models.ManyToManyField(blank=True, related_name='biens', to='patrimoine.photobien'),
        ),
    ]
