# Generated by Django 6.0.3 on 2026-03-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0004_bien_modele_3d_photobien_bien_photos_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='motif_rejet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('LOUE', 'Loué'), ('VACANT', 'Vacant'), ('EN_TRAVAUX', 'En travaux'), ('EN_VENTE', 'En vente'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('REJETE', 'Rejeté')], default='VACANT', max_length=25),
        ),
    ]
