# Generated by Django 6.0.3 on 2026-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0005_bien_motif_rejet_alter_bien_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='bail_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='visite_en_cours',
            field=models.BooleanField(default=False),
        ),
    ]
