# Generated by Django 6.0.3 on 2026-03-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimoine', '0006_bien_bail_actif_bien_visite_en_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='taux_commission',
            field=models.FloatField(default=0),
        ),
    ]
