# Generated by Django 6.0.3 on 2026-03-26 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locataires', '0003_initial'),
        ('patrimoine', '0006_bien_bail_actif_bien_visite_en_cours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitebien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('EFFECTUEE', 'Effectuée')], default='EN_ATTENTE', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='patrimoine.bien')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='BienSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauvegardes', to='patrimoine.bien')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens_sauvegardes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien sauvegardé',
                'verbose_name_plural': 'Biens sauvegardés',
                'ordering': ['-created_at'],
                'unique_together': {('bien', 'client')},
            },
        ),
    ]
